import zipfile
import json
import logging
import xml.etree.ElementTree as ET

from ..model import Model
from ..language import LanguageGraph

logger = logging.getLogger(__name__)

def load_model_from_scad_archive(
        scad_archive: str,
        lang_graph: LanguageGraph,
    ) -> tuple[Model, dict]:
    """
    Reads a '.sCAD' archive generated by securiCAD representing an instance
    model and loads the information into a maltoobox.model.Model object.

    Arguments:
    scad_archive            - the path to a '.sCAD' archive
    lang_graph              - a language graph representing the MAL
                              language specification
    lang_classes_factory    - a language classes factory that contains
                              the classes defined by the
                              language specification

    Return:
    A maltoobox.model.Model object containing the instance model.
    """

    attacker_configs = {}
    with zipfile.ZipFile(scad_archive, 'r') as archive:
        filelist = archive.namelist()
        model_file = next(filter(lambda x: ( x[-4:] == '.eom'), filelist))
        scad_model = archive.read(model_file)
        root = ET.fromstring(scad_model)

    instance_model = Model(scad_archive, lang_graph)

    for child in root.iter('objects'):

        if child.attrib['metaConcept'] == 'Attacker':
            attacker_id = int(child.attrib['id'])
            attacker_configs[attacker_id] = {
                'id': child.attrib['id'],
                'name': child.attrib['name']
            }

        elif child.attrib['metaConcept'] in lang_graph.assets:
            asset = lang_graph.assets[child.attrib['metaConcept']]
            asset_id = int(child.attrib['id'])
            asset_name = child.attrib['name']
            for subchild in child.iter('evidenceAttributes'):
                defense_name = subchild.attrib['metaConcept']
                defense_name = defense_name[0].lower() + defense_name[1:]
                for distrib in subchild.iter('evidenceDistribution'):
                    for d in distrib.iter('parameters'):
                        if 'value' in d.attrib:
                            dist_value = d.attrib['value']
                            setattr(asset, defense_name, float(dist_value))
            instance_model.add_asset(asset.name, name=asset_name, asset_id=asset_id)

        else:
            raise ValueError(
                f'Failed to find {child.attrib["metaConcept"]}'
                ' asset in language specification!'
            )

    for child in root.iter('associations'):
        logger.debug(
            'Load association ("%s", "%s", "%s", "%s") from %s',
            child.attrib["sourceObject"], child.attrib["targetObject"],
            child.attrib["targetProperty"], child.attrib["sourceProperty"],
            scad_archive
        )

        # Note: This is not a bug in the code. The fields and assets are
        # listed incorrectly in the securiCAD format where the source asset
        # matches the target field and vice versa.
        left_id = int(child.attrib['targetObject'])
        right_id = int(child.attrib['sourceObject'])
        attacker_id = None

        if child.attrib['sourceProperty'] == 'firstSteps':
            attacker_id = right_id
            target_id = left_id
            target_prop = child.attrib['targetProperty']
        elif child.attrib['targetProperty'] == 'firstSteps':
            attacker_id = left_id
            target_id = right_id
            target_prop = child.attrib['sourceProperty']

        if attacker_id:
            attacker = attacker_configs[attacker_id]
            target_asset = instance_model.get_asset_by_id(target_id)
            if not target_asset:
                raise LookupError(
                    f'Failed to find asset with id {target_id} in model!'
                )
            attacker.setdefault('entry_points', []).append((target_asset, target_prop))
        else:
            left_asset = instance_model.get_asset_by_id(left_id)
            if not left_asset:
                raise LookupError(
                    f'Failed to find asset with {left_id} in model!'
                )
            right_asset = instance_model.get_asset_by_id(right_id)
            if not right_asset:
                breakpoint()
                raise LookupError(
                    f'Failed to find asset with id {right_id} in model!'
                )
            try:
                right_asset.add_associated_assets(child.attrib['sourceProperty'], {left_asset})
            except TypeError:
                breakpoint()

    return instance_model, attacker_configs