[package]
name = "maltoolbox-language"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
maltoolbox-fileutil = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-mal = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
slotmap = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
maltoolbox-model = { workspace = true }
maltoolbox-attackgraph = { workspace = true }
