name: Pytest maltoolbox
on: push

jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
          python -m pip install --upgrade pip
          pip install .
      - name: Test with pytest
        run: |
          pip install pytest
          pytest tests -m "not integration"
